language: minimal
sudo: required
services:
env:
  global:
  - REPO_NAME=hugocoinbot
before_install:
script:
- zip -r app.zip src package.json
deploy:
  skip_cleanup: true
  zip_file: app.zip
  provider: elasticbeanstalk
  access_key_id:
    secure: "JRSrmI/9JZWmp5nuC9IG4j3w/CNlSix1n1sYAmDdNzOB2r0fZNJ8jJ2cjkC0B6n5MEVDR6x/MfOc5owKOxOAF3dlHjxU3x3EvuL3u0Lu54aRztE6AUKr886QKO2R6HZnFQeDUmomc0TzUz9raaE8mapniISe5vAuMCCRSMCR7peMXcdX9unLplDSslRy2boJf9u9Cn4P/z5857QapskAE7nbBgyL9h1CDk0oMrDluFlDBNtldXOIGaYniLHApXWJ3YwHCMVg1ewgBZEIVBWhzxV2n8UELzGxzD8/Hc82SqVZr+LkkmzvEaIwZi1Zdigq+jXGhIDatO0XKeKeGLlG4LnDUPz7rR8qMy5QLaQm9/INA1W55C9Vpyw5wr/X8i54L+D8YpBTFIM7nBOQOjyWX9EOf+ilkhabrf42PB9QJydSg9d8mxQzPK1luCI2XnDRSVg3QpMoW8dUaiDcVfZalZnKeR7ap4dOBtYVQ3jeAIfb963XX2yGXeewETJXVboLjq8KUdT3mwhRxqBy6NkyIhehp/tEmqGtLNhf9uQQkxy+P3AXFRyoKlgOaU8rDoKspmp93QPzA0zyfbDEjXVyRX0oVkTEEZCslxssfnQ0vpSTmjRJiu1pLDFqSQ3vBjvRNvve/+YED+akDkVGIznymZuFDzhNvQRAEVw7Fs48Hlg="
  secret_access_key:
    secure: "knv17iPKD7Ok4f6WOu7sIlr0DbfEyN7W3c7VMZaRp1spU7/dpOclq49FVes4t9y4o69JMrF0r3q+yoK7wMGBitkcyHbY9pIhJpCiX8x1WUEOi/VmKnVJDyMLlH4DJ5HR1Ok3oLdA5qd6ZyzeNPP+cVqkeFVhMM6tV6MDiJQDD/DW4cdFOgi+K/Int0i+4+3KQdD22KWT4fmXQu/ORhNl6sr+wCSXk6XR/0RxqfRtlZbi4gfZ6fwXlzPLcVELg4rcFctAKH5bE2c40ivwWArj5e54u8+7u/Y/PcUDhvwDkEQH1SxI5PgAkOdisV4lum9kQu9dXV+v85Bc0+uxov1JjNluqz8JxZIqfK0IAssyYxdDz7XOJWDe9F6pCtYZX6J/fHCqQWLl02hh9Um08xH8dmUVMyWqjhwhF/4A6f1Q3o27vKJRUerbWttn599uiO+PPP2dEC2YqEd2HIsnBXVW5QLNcwD3TLPptDTC+BOgSgaPZ8h/5Ian5H3JAnD+OT5DnOQ7KUahRF93BtsK3NlhQJdqPDJZKHq99fspNL5qaKK7eebnTk7olhtJ4SrS28WyqcWAWaaFUcHD7XNjPdxmbJgiPVZLGIHw5MxyTtNhrJAuz4pvDUx0ovRULvT6rMy7rAxp2GOmCveg/A3WwW8wvsbhPq6yC2yhIv5wMN2JR6g="
  region: us-east-2
  app: hugocoinbot
  env: Hugocoinbot-dev
  bucket_name: hugocoinbot-eb
  on:
    repo: tanelso2/hugocoinbot
    branch: master
